let firstName ="Nduka";
let lastName = "Kingsley";
let country = "Nigeria";
let city = "Lagos";
let age = 21;
let isMarried = true;
let year = 2023;
console.log(typeof lastName);
console.log(typeof age);
console.log(`${isMarried}`);
console.log('10'==10);
console.log('10'===10);
console.log(parseInt(9.8)===10);
console.log(parseFloat(9.8)===10);
console.log("Nduka".length === "kingsley".length);
console.log("Nduka".length !== "kingsley".length);